<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PackageId>Notification.KafkaMessages</PackageId>
        <Title>Notification.KafkaMessages</Title>
        <Authors>nikitaberezhko</Authors>
        <Description>Сообщения, потребляемые микросервисом Notification.</Description>
        <PackageIcon>icon.png</PackageIcon>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageProjectUrl>https://gitlab.com/carsharing-backend</PackageProjectUrl>
        <RepositoryUrl>https://gitlab.com/carsharing-backend/contracts/kafka/notificationkafkamessages</RepositoryUrl>
        <Version>1.0.1</Version>
    </PropertyGroup>

    <ItemGroup>
        <None Update="icon.png">
            <Pack>True</Pack>
            <PackagePath></PackagePath>
        </None>
    </ItemGroup>

</Project>
